$:
  push:
    # 导入密钥仓库文件为环境变量
    - imports:
        - https://cnb.cool/tencent/tdesign/tdesign-private/-/blob/main/cnb-envs.yml
      stages:
        - name: sync to github with rebase
          image: tencentcom/git-sync
          settings:
            target_url: https://github.com/Tencent/tdesign-flutter.git
            auth_type: https
            username: ${GIT_USERNAME}
            password: ${GIT_ACCESS_TOKEN}

  # 自定义 NPC「tdesign-flutter-npc」事件流水线
  # 参考文档：https://docs.cnb.cool/zh/build/npc.md
  issue.comment@npc:
    - docker:
        image: docker.cnb.cool/tencent/tdesign/default-dev-env:latest
      stages:
        - name: npc go
          type: npc:go

  pull_request.comment@npc:
    - docker:
        image: docker.cnb.cool/tencent/tdesign/default-dev-env:latest
      stages:
        - name: npc go
          type: npc:go

  vscode:
    - docker:
        image: docker.cnb.cool/tencent/tdesign/default-dev-env:latest
      services:
        - vscode
        - docker
      stages:
        - name: install component dependencies
          script: cd tdesign-component && flutter pub get

        - name: install example dependencies
          script: cd tdesign-component/example && flutter pub get

        - name: install site dependencies
          script: cd tdesign-site && pnpm install
