name: 反馈 Bug
description: 通过 github 模板进行 Bug 反馈。
title: "[组件名称] 描述问题的标题"
body:
  - type: markdown
    attributes:
      value: |
        # 欢迎你的参与
        tdesign-flutter 的 Issue 列表接受 bug 报告或是新功能请求。也可加入官方社区：
        
        <img width="200px" src="https://tdesign.tencent.com/flutter/assets/qrcode/feedback.png" />

        在发布一个 Issue 前，请确保：
          - 在 [常见问题](https://github.com/Tencent/tdesign-flutter/blob/main/tdesign-site/FAQ.md)、[更新日志](https://tdesign.tencent.com/flutter/changelog) 和 [Issue列表](https://github.com/Tencent/tdesign-flutter/issues) 中搜索过你的问题。（你的问题可能已有人提出，也可能已在最新版本中被修正）
          - 如果你发现一个已经关闭的旧 Issue 在最新版本中仍然存在，不要在旧 Issue 下面留言，请建一个新的 issue。

  - type: input
    id: version
    attributes:
      label: tdesign-flutter 版本
      description: 请检查在最新项目版本中能否重现此 issue。
      placeholder: 请填写
    validations:
      required: true

  - type: input
    id: reproduce
    attributes:
      label: 重现链接
      description: 请提供尽可能精简的 CodePen、CodeSandbox 或 GitHub 仓库的链接。请不要填无关链接，否则你的 Issue 将被关闭。
      placeholder: 请填写

  - type: textarea
    id: reproduceSteps
    attributes:
      label: 重现步骤/代码
      description: 请清晰的描述重现该 Issue 的步骤，这能帮助我们快速定位问题。没有清晰重现步骤将不会被修复，标有 'need reproduction' 的 Issue 在 7 天内不提供相关步骤，将被关闭。
      placeholder: 请填写

  - type: textarea
    id: expect
    attributes:
      label: 期望结果
      placeholder: 请填写

  - type: textarea
    id: actual
    attributes:
      label: 实际结果
      placeholder: 请填写

  - type: input
    id: flutterVersion
    attributes:
      label: Flutter版本
      placeholder: Flutter(2.2.0)

  - type: input
    id: deviceInfo
    attributes:
      label: 设备与机型信息
      placeholder: Android(vivo V2005A)/iOS(iphone 12)

  - type: input
    id: systemVersion
    attributes:
      label: 系统版本
      placeholder: iOS 9.3/Android 10/emulator/simulator

  - type: textarea
    id: remarks
    attributes:
      label: 补充说明
      description: 可以是遇到这个 bug 的业务场景、上下文等信息。
      placeholder: 请填写
