name: autofix.ci
on:
  pull_request:
    branches: [develop]
    paths-ignore:
      - "tdesign-site/**"
      - "*.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Flutter
        uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2.23.0
        with:
          flutter-version: 3.32.0
          cache: true

      - name: generate api md
        working-directory: ./tdesign-component
        run: sh ./demo_tool/all_build.sh

      - name: Check example code snippets
        working-directory: ./tdesign-component
        run: dart run tool/generate_example_code.dart --check

      - name: flutter pub get
        working-directory: ./tdesign-component/example
        run: flutter pub get

      - name: flutter build
        working-directory: ./tdesign-component/example
        run: flutter build apk -t ./lib/main.dart --release

      - name: Sync README files
        run: node scripts/sync-readme.mjs

      - uses: autofix-ci/action@v1
