name: ci

on:
  pull_request:
    branches: [develop, main]
    types: [opened, synchronize, reopened]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.16.9"
          cache: true

      - run: flutter --version

      - name: flutter pub get
        working-directory: ./tdesign-component
        run: flutter pub get

      - name: flutter build
        working-directory: ./tdesign-component/example
        run: flutter build apk

      - name: upload apk
        uses: actions/upload-artifact@v4
        id: upload-apk
        with:
          name: tdesign-flutter-example.apk
          path: tdesign-component/example/build/app/outputs/flutter-apk/app-release.apk
          retention-days: 5

  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.16.9"
          cache: true

      - run: flutter --version

      - name: flutter pub get
        working-directory: ./tdesign-component
        run: flutter pub get

      - name: flutter build
        working-directory: ./tdesign-component/example
        run: flutter build ios --release --no-codesign

  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.16.9"
          cache: true

      - run: flutter --version

      - name: flutter pub get
        working-directory: ./tdesign-component
        run: flutter pub get

      - name: flutter build
        working-directory: ./tdesign-component/example
        run: flutter build web
