
name: Push Test
on:
  push:
    branches: [develop, feature/actions, main]

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Luozf
        MIDDLE_NAME: The
        LAST_NAME: 12345
      run: |
        echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
